### ISSUE TITLE
[Enhancement]: NPM or PNPM 

### ISSUE THREAD

**Issue by leoalipazaga** [Afordin/aforshow-2024#37]
### What problem would you like to solve or improve?

People we have to choose between `pnpm` or `npm` as package mangement. It's not a good practice keep both them.

### Describe your proposed solution or enhancement.

- Choose `pnpm` or `npm`
- Remove `package-lock.json` or `pnpm-lock.yaml`

<img width="582" alt="image" src="https://github.com/user-attachments/assets/2f5e18ac-1872-4340-a3b0-ccb05b6a60a6">

### Describe any alternative solutions you've considered (optional).

I would recommend `pnpm`. It is faster than `npm`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by afordigital** [comment]
Thank you for the issuse, solved! 🐭
